[general]
    # benchmark name
    name = 'Clojure benchmarks'
    # select the most applicable category from the list provided by this repo
    category = 'PERFORMANCE'
    # mark your benchmark with custom tags (your own custom tags OR use existing from other projects)
    tags = ['performance ', 'language',]

[info]
    # programming language
    language = 'Clojure'
    # license used in the project from the list provided by this repo
    license = 'NO'
    # number of tests/cases/scenarios/benchmarks (should not be 0)
    scenarios_num = 500
    # free text with a small desciption of the benchmark
    description = 'Benchmark programs in Clojure, Java, and several other languages, for performance comparison'

[links]
    # the link to the home page of the benchmark
    homepage = 'https://github.com/jafingerhut/clojure-benchmarks'
    # the link to the source code
    sources = 'https://github.com/jafingerhut/clojure-benchmarks'
    # the link to the page with documentation
    documentation = 'https://github.com/jafingerhut/clojure-benchmarks'
