[general]
    # benchmark name
    name = 'ISO 26262'
    # select the most applicable category from the list provided by this repo
    category = 'CODING_STANDARD'
    # mark your benchmark with custom tags (your own custom tags OR use existing from other projects)
    tags = ['coding_standard', 'security']

[info]
    # programming language
    language = 'Agnostic'
    # license used in the project from the list provided by this repo
    license = 'ISO Customer Licence Agreement'
    # number of tests/cases/scenarios/benchmarks (should not be 0)
    scenarios_num = 12
    # free text with a small desciption of the benchmark
    description = 'ISO 26262 mandates a functional safety development process (from specification all the way through production release) that automotive OEMs and suppliers must follow and document (for compliance) to have their devices qualified to run inside commercial (passenger) vehicles.'

[links]
    # the link to the home page of the benchmark
    homepage = 'https://www.iso.org/standards.html'
    # the link to the source code
    sources = 'https://www.iso.org/standard/68383.html'
    # the link to the page with documentation
    documentation = 'https://www.iso.org/standard/68383.html'