[general]
    # benchmark name
    name = 'ISO/IEC TS 17961 C Secure Coding Rules'
    # select the most applicable category from the list provided by this repo
    category = 'CODE_ANALYSIS'
    # mark your benchmark with custom tags (your own custom tags OR use existing from other projects)
    tags = ['code_analysis', 'c']

[info]
    # programming language
    language = 'c'
    # license used in the project from the list provided by this repo
    license = 'ISO Customer Licence Agreement'
    # number of tests/cases/scenarios/benchmarks (should not be 0)
    scenarios_num = 45
    # free text with a small desciption of the benchmark
    description = 'The purpose of ISO/IEC TS 17961 [ISO/IEC TS 17961:2013] is to establish a baseline set of requirements for analyzers, including static analysis tools and C language compilers.'

[links]
    # the link to the home page of the benchmark
    homepage = 'https://www.iso.org/standards.html'
    # the link to the source code
    sources = 'https://www.iso.org/standard/61134.html'
    # the link to the page with documentation
    documentation = 'https://www.iso.org/standard/61134.html'